version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./back.Dockerfile
    ports:
      - 8080:8080

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./front.Dockerfile
    ports:
      - 5000:5000
